[colors]
background = '#09170c8e'
black = '#09170c'
blue = '#578B77'
cursor = '#c1c5c2'
cyan = '#C88B73'
foreground = '#c1c5c2'
green = '#286C8E'
magenta = '#BE6B8A'
red = '#54ABA9'
tabs = '#c1c5c2'
tabs-active = '#BFB5AD'
white = '#c1c5c2'
yellow = '#c1c5c2'
dim-black = '#09170c8e'
dim-blue = '#578B778e'
dim-cyan = '#C88B738e'
dim-foreground = '#c1c5c28e'
dim-green = '#286C8E8e'
dim-magenta = '#BE6B8A8e'
dim-red = '#54ABA98e'
dim-white = '#BFB5AD8e'
dim-yellow = '#c1c5c28e'
light-black = '#578B77'
light-blue = '#C88B73'
light-cyan = '#286C8E'
light-foreground = '#BE6B8A'
light-green = '#54ABA9'
light-magenta = '#BFB5AD'
light-red = '#c1c5c2'
light-white = '#578B77'
light-yellow = '#C88B73'
