[colors]
background = '#3024258e'
black = '#302425'
blue = '#75BDCE'
cursor = '#cbc8c8'
cyan = '#C2AAB2'
foreground = '#cbc8c8'
green = '#E1A4AC'
magenta = '#EECEA8'
red = '#9DDBDF'
tabs = '#cbc8c8'
tabs-active = '#DFD5DE'
white = '#cbc8c8'
yellow = '#cbc8c8'
dim-black = '#3024258e'
dim-blue = '#75BDCE8e'
dim-cyan = '#C2AAB28e'
dim-foreground = '#cbc8c88e'
dim-green = '#E1A4AC8e'
dim-magenta = '#EECEA88e'
dim-red = '#9DDBDF8e'
dim-white = '#DFD5DE8e'
dim-yellow = '#cbc8c88e'
light-black = '#75BDCE'
light-blue = '#C2AAB2'
light-cyan = '#E1A4AC'
light-foreground = '#EECEA8'
light-green = '#9DDBDF'
light-magenta = '#DFD5DE'
light-red = '#cbc8c8'
light-white = '#75BDCE'
light-yellow = '#C2AAB2'
