# Shell variables
# Generated by 'wal'
wallpaper="/home/eris/Pictures/wallpapers/ayame-chill.png"

# Special
background='#302425'
foreground='#cbc8c8'
cursor='#cbc8c8'

# Colors
color0='#302425'
color1='#75BDCE'
color2='#C2AAB2'
color3='#E1A4AC'
color4='#EECEA8'
color5='#9DDBDF'
color6='#DFD5DE'
color7='#cbc8c8'
color8='#7f686b'
color9='#75BDCE'
color10='#C2AAB2'
color11='#E1A4AC'
color12='#EECEA8'
color13='#9DDBDF'
color14='#DFD5DE'
color15='#cbc8c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
