foreground         #cbc8c8
background         #302425
background_opacity 1.0
cursor             #cbc8c8

active_tab_foreground     #302425
active_tab_background     #cbc8c8
inactive_tab_foreground   #cbc8c8
inactive_tab_background   #302425

active_border_color   #cbc8c8
inactive_border_color #302425
bell_border_color     #75BDCE

color0       #302425
color8       #7f686b
color1       #75BDCE
color9       #75BDCE
color2       #C2AAB2
color10      #C2AAB2
color3       #E1A4AC
color11      #E1A4AC
color4       #EECEA8
color12      #EECEA8
color5       #9DDBDF
color13      #9DDBDF
color6       #DFD5DE
color14      #DFD5DE
color7       #cbc8c8
color15      #cbc8c8
