# Shell variables
# Generated by 'wal'
wallpaper="/home/eris/Pictures/wallpapers/totoro.png"

# Special
background='#070711'
foreground='#c1c1c3'
cursor='#c1c1c3'

# Colors
color0='#070711'
color1='#504364'
color2='#564769'
color3='#77628d'
color4='#977bb8'
color5='#a384c2'
color6='#a985ad'
color7='#c1c1c3'
color8='#56566a'
color9='#504364'
color10='#564769'
color11='#77628d'
color12='#977bb8'
color13='#a384c2'
color14='#a985ad'
color15='#c1c1c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
