[colors.primary]
background = "#302425"
foreground = "#cbc8c8"

[colors.cursor]
text = "#302425"
cursor = "#cbc8c8"

[colors.vi_mode_cursor]
text = "#302425"
cursor = "#cbc8c8"

[colors.search.matches]
foreground = "#302425"
background = "#cbc8c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#7f686b"
background = "#cbc8c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#302425"
red = "#75BDCE"
green = "#C2AAB2"
yellow = "#E1A4AC"
blue = "#EECEA8"
magenta = "#9DDBDF"
cyan = "#DFD5DE"
white = "#cbc8c8"

[colors.bright]
black = "#7f686b"
red = "#75BDCE"
green = "#C2AAB2"
yellow = "#E1A4AC"
blue = "#EECEA8"
magenta = "#9DDBDF"
cyan = "#DFD5DE"
white = "#cbc8c8"

[colors.dim]
black = "#cbc8c8"
red = "#75BDCE"
green = "#9DDBDF"
yellow = "#E1A4AC"
blue = "#EECEA8"
magenta = "#C2AAB2"
cyan = "#DFD5DE"
white = "#7f686b"

