# Shell variables
# Generated by 'wal'
wallpaper="/home/eris/Pictures/wallpapers/Wallpaper1.jpg"

# Special
background='#09170c'
foreground='#c1c5c2'
cursor='#c1c5c2'

# Colors
color0='#09170c'
color1='#578B77'
color2='#C88B73'
color3='#286C8E'
color4='#BE6B8A'
color5='#54ABA9'
color6='#BFB5AD'
color7='#c1c5c2'
color8='#596d5d'
color9='#578B77'
color10='#C88B73'
color11='#286C8E'
color12='#BE6B8A'
color13='#54ABA9'
color14='#BFB5AD'
color15='#c1c5c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
