--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/eris/Pictures/wallpapers/ayame-chill.png"

-- Special
background="#302425"
foreground="#cbc8c8"
cursor="#cbc8c8"

-- Colors
color0="#302425"
color1="#75BDCE"
color2="#C2AAB2"
color3="#E1A4AC"
color4="#EECEA8"
color5="#9DDBDF"
color6="#DFD5DE"
color7="#cbc8c8"
color8="#7f686b"
color9="#75BDCE"
color10="#C2AAB2"
color11="#E1A4AC"
color12="#EECEA8"
color13="#9DDBDF"
color14="#DFD5DE"
color15="#cbc8c8"
