--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/eris/Pictures/wallpapers/totoro.png"

-- Special
background="#070711"
foreground="#c1c1c3"
cursor="#c1c1c3"

-- Colors
color0="#070711"
color1="#504364"
color2="#564769"
color3="#77628d"
color4="#977bb8"
color5="#a384c2"
color6="#a985ad"
color7="#c1c1c3"
color8="#56566a"
color9="#504364"
color10="#564769"
color11="#77628d"
color12="#977bb8"
color13="#a384c2"
color14="#a985ad"
color15="#c1c1c3"
