--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/eris/Pictures/wallpapers/Wallpaper1.jpg"

-- Special
background="#09170c"
foreground="#c1c5c2"
cursor="#c1c5c2"

-- Colors
color0="#09170c"
color1="#578B77"
color2="#C88B73"
color3="#286C8E"
color4="#BE6B8A"
color5="#54ABA9"
color6="#BFB5AD"
color7="#c1c5c2"
color8="#596d5d"
color9="#578B77"
color10="#C88B73"
color11="#286C8E"
color12="#BE6B8A"
color13="#54ABA9"
color14="#BFB5AD"
color15="#c1c5c2"
