foreground         #c1c1c3
background         #070711
background_opacity 1.0
cursor             #c1c1c3

active_tab_foreground     #070711
active_tab_background     #c1c1c3
inactive_tab_foreground   #c1c1c3
inactive_tab_background   #070711

active_border_color   #c1c1c3
inactive_border_color #070711
bell_border_color     #504364

color0       #070711
color8       #56566a
color1       #504364
color9       #504364
color2       #564769
color10      #564769
color3       #77628d
color11      #77628d
color4       #977bb8
color12      #977bb8
color5       #a384c2
color13      #a384c2
color6       #a985ad
color14      #a985ad
color7       #c1c1c3
color15      #c1c1c3
