[colors]
background = '#0707118e'
black = '#070711'
blue = '#504364'
cursor = '#c1c1c3'
cyan = '#564769'
foreground = '#c1c1c3'
green = '#77628d'
magenta = '#977bb8'
red = '#a384c2'
tabs = '#c1c1c3'
tabs-active = '#a985ad'
white = '#c1c1c3'
yellow = '#c1c1c3'
dim-black = '#0707118e'
dim-blue = '#5043648e'
dim-cyan = '#5647698e'
dim-foreground = '#c1c1c38e'
dim-green = '#77628d8e'
dim-magenta = '#977bb88e'
dim-red = '#a384c28e'
dim-white = '#a985ad8e'
dim-yellow = '#c1c1c38e'
light-black = '#504364'
light-blue = '#564769'
light-cyan = '#77628d'
light-foreground = '#977bb8'
light-green = '#a384c2'
light-magenta = '#a985ad'
light-red = '#c1c1c3'
light-white = '#504364'
light-yellow = '#564769'
