# pywal theme for ghostty

background = 09170c
foreground = c1c5c2
cursor-color = c1c5c2
selection-background = c1c5c2
selection-foreground = 09170c

palette = 0=#09170c
palette = 1=#578B77
palette = 2=#C88B73
palette = 3=#286C8E
palette = 4=#BE6B8A
palette = 5=#54ABA9
palette = 6=#BFB5AD
palette = 7=#c1c5c2
palette = 8=#596d5d
palette = 9=#578B77
palette = 10=#C88B73
palette = 11=#286C8E
palette = 12=#BE6B8A
palette = 13=#54ABA9
palette = 14=#BFB5AD
palette = 15=#c1c5c2
