# pywal theme for ghostty

background = 070711
foreground = c1c1c3
cursor-color = c1c1c3
selection-background = c1c1c3
selection-foreground = 070711

palette = 0=#070711
palette = 1=#504364
palette = 2=#564769
palette = 3=#77628d
palette = 4=#977bb8
palette = 5=#a384c2
palette = 6=#a985ad
palette = 7=#c1c1c3
palette = 8=#56566a
palette = 9=#504364
palette = 10=#564769
palette = 11=#77628d
palette = 12=#977bb8
palette = 13=#a384c2
palette = 14=#a985ad
palette = 15=#c1c1c3
