# pywal theme for ghostty

background = 302425
foreground = cbc8c8
cursor-color = cbc8c8
selection-background = cbc8c8
selection-foreground = 302425

palette = 0=#302425
palette = 1=#75BDCE
palette = 2=#C2AAB2
palette = 3=#E1A4AC
palette = 4=#EECEA8
palette = 5=#9DDBDF
palette = 6=#DFD5DE
palette = 7=#cbc8c8
palette = 8=#7f686b
palette = 9=#75BDCE
palette = 10=#C2AAB2
palette = 11=#E1A4AC
palette = 12=#EECEA8
palette = 13=#9DDBDF
palette = 14=#DFD5DE
palette = 15=#cbc8c8
